### ISSUE TITLE
Unable to Update from v1.5.10 and can't open app due to "connect_failed SytanxError: Unexpected token < in JSON at position 0"

### ISSUE THREAD

**Issue by ndzi2** [snapcrafters/yakyak#24]
Was having trouble opening the app using the desktop icon on ubuntu 20.04 when it got stuck on the "Connecting" page. Tried opening in the terminal and got the following output:

    Starting Yakyak v1.5.10...
    using hangupsjs v1.3.10
    --------
    hangupsjs:: connecting
    reconnecting 0
    resolving proxy http://plus.google.com
    resolving proxy https://plus.google.com
    resolved proxy DIRECT
    resolved proxy DIRECT
    2021-04-13 23:44:22 INFO fetchPvt failed Unexpected token < in JSON at position 0
    connect_failed SyntaxError: Unexpected token < in JSON at position 0
        at JSON.parse (<anonymous>)
        at /snap/yakyak/91/yakyak/resources/app.asar/node_modules/hangupsjs/lib/channel.js:117:21
        at _fulfilled (/snap/yakyak/91/yakyak/resources/app.asar/node_modules/q/q.js:854:54)
        at /snap/yakyak/91/yakyak/resources/app.asar/node_modules/q/q.js:883:30
        at Promise.promise.promiseDispatch (/snap/yakyak/91/yakyak/resources/app.asar/node_modules/q/q.js:816:13)
        at /snap/yakyak/91/yakyak/resources/app.asar/node_modules/q/q.js:624:44
        at runSingle (/snap/yakyak/91/yakyak/resources/app.asar/node_modules/q/q.js:137:13)
        at flush (/snap/yakyak/91/yakyak/resources/app.asar/node_modules/q/q.js:125:13)
        at processTicksAndRejections (internal/process/task_queues.js:79:11)
    error connecting SyntaxError: Unexpected token < in JSON at position 0
        at JSON.parse (<anonymous>)
        at /snap/yakyak/91/yakyak/resources/app.asar/node_modules/hangupsjs/lib/channel.js:117:21
        at _fulfilled (/snap/yakyak/91/yakyak/resources/app.asar/node_modules/q/q.js:854:54)
        at /snap/yakyak/91/yakyak/resources/app.asar/node_modules/q/q.js:883:30
        at Promise.promise.promiseDispatch (/snap/yakyak/91/yakyak/resources/app.asar/node_modules/q/q.js:816:13)
        at /snap/yakyak/91/yakyak/resources/app.asar/node_modules/q/q.js:624:44
        at runSingle (/snap/yakyak/91/yakyak/resources/app.asar/node_modules/q/q.js:137:13)
        at flush (/snap/yakyak/91/yakyak/resources/app.asar/node_modules/q/q.js:125:13)
        at processTicksAndRejections (internal/process/task_queues.js:79:11)

Dig some digging and the github repo is up to v1.5.12 which apparently has fixed this issue, and the snapcraft repo says it is up to v1.5.11 but when I run `sudo snap refresh yakyak` I can't update past v1.5.10.

**Comment by popey** [comment]
Thanks for filing the issue, but as this software is now abandoned, I'm going to close all issues and archive the project.
